services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        ENABLE_XDEBUG: "0"        # mets "1" ponctuellement
    container_name: symfony_php
    ports: 
      - "${APP_PORT:-8080}:8000"
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: "1"
      DATABASE_URL: "mysql://${MYSQL_USER:-symfony}:${MYSQL_PASSWORD:-symfony}@db:3306/${MYSQL_DATABASE:-symfony}"
    volumes:
      - .:/var/www/html:delegated             # code (bind)
      - symfony-cache:/var/www/html/var/cache # volume docker
      - symfony-logs:/var/www/html/var/log    # volume docker
      - /var/www/html/vendor                  # cache le vendor du host -> utilise celui de l'image
      - ./public/avatars:/var/www/html/public/avatars
      - ./public/homeworks:/var/www/html/public/homeworks
      - ./public/internships:/var/www/html/public/internships
    command: >
      sh -lc "mkdir -p var/cache var/log &&
              chown -R www-data:www-data var &&
              exec symfony server:start --no-tls --allow-all-ip"
    depends_on:
      - db

  node:
    image: node:20
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/app:delegated
      - /app/node_modules            # volume anonyme (pas de bind host)

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql_symfony
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony}
      MYSQL_USER: ${MYSQL_USER:-symfony}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  symfony-cache:
  symfony-logs:
  db_data:
