controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
admin:
    path: /{_locale}/admin
    controller: App\Controller\Admin\DashboardController::index
    requirements:
        _locale: fr|en|es